{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This script performs a Bayesian Additive Regression Trees analysis of the nanoQSAR data.\n",
    "#\n",
    "# Created: 01/02/2018 Wilson Melendez\n",
    "# Revised: \n",
    "\n",
    "# Set the location of scripts.\n",
    "working_directory <- \"C:/Users/wmelende/RnanoQSAR/R-nanoQSAR\"\n",
    "\n",
    "# Set working directory\n",
    "setwd(working_directory)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load external functions into this script.\n",
    "source(\"runJarFile.R\")\n",
    "source(\"extractNumericColumns.R\")\n",
    "source(\"extractXcolumns.R\")\n",
    "source(\"extractYcolumn.R\")\n",
    "source(\"getRecordswithResults.R\")\n",
    "source(\"removeColumnsWithAllNAs.R\")\n",
    "source(\"removeColumnsWithOneRepeatedValue.R\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define string with location of Jar File\n",
    "jarFolder <- working_directory\n",
    "\n",
    "# Call function that will run Jar file.\n",
    "runJarFile(jarFolder)\n",
    "\n",
    "# Read in CSV file.\n",
    "filename <- paste(jarFolder, \"/nanoQSAR.csv\", sep=\"\")\n",
    "nanoQSARdata <- read.csv(filename, stringsAsFactors=FALSE)\n",
    "\n",
    "# Extract numeric columns\n",
    "numericData <- extractNumericColumns(nanoQSARdata)\n",
    "\n",
    "# Get the records with results\n",
    "trainingData <- getRecordswithResults(numericData)\n",
    "\n",
    "# Extract the X matrix.\n",
    "XmatrixOrig <- extractXcolumns(trainingData)\n",
    "\n",
    "# Extract results column.\n",
    "Ymatrix <- extractYcolumn(trainingData)\n",
    "\n",
    "# Convert Y matrix to numeric \n",
    "y = as.numeric(Ymatrix)\n",
    "\n",
    "# Check whether the X matrix has columns with no values (all NAs), and if so remove those columns.\n",
    "Xmatrix <- removeColumnsWithAllNAs(XmatrixOrig)\n",
    "\n",
    "# Check whether the X matrix has columns with only a single value that is repeated throughout the column.\n",
    "Xmatrix <- removeColumnsWithOneRepeatedValue(Xmatrix)\n",
    "\n",
    "# Set JAVA_HOME to the location of the JDK in your system.\n",
    "Sys.setenv(\"JAVA_HOME\"=\"C:\\\\Program Files\\\\Java\\\\jdk1.8.0_152\")\n",
    "\n",
    "#  Get the location of the JDK\n",
    "Sys.getenv(\"JAVA_HOME\")\n",
    "\n",
    "# Load the rJava package -- this is needed by the bartMachine.\n",
    "library(rJava)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Allocate memory needed before loading the bartMachine.\n",
    "# Note that the maximum amount of memory can be set only once at the beginning of the R session (a\n",
    "# limitation of rJava since only one Java Virtual Machine can be initiated per R session), but the number of\n",
    "# cores can be respecified at any time.\n",
    "options(java.parameters = \"-Xmx2000m\")\n",
    "\n",
    "# Load the bartMachine package\n",
    "library(bartMachine)\n",
    "\n",
    "# Allocate number of cores that will be used by the bartMachine\n",
    "set_bart_machine_num_cores(4)\n",
    "\n",
    "# Call the bartMachine\n",
    "bart_machine <- bartMachine(Xmatrix, y, \n",
    "                            num_trees = 200,\n",
    "                            num_burn_in = 250,\n",
    "                            num_iterations_after_burn_in = 1000,\n",
    "                            alpha = 0.95, beta = 2, k = 2, q = 0.9, nu = 3,\n",
    "                            prob_rule_class = 0.5,\n",
    "                            mh_prob_steps = c(2.5, 2.5, 4)/9,\n",
    "                            debug_log = FALSE,\n",
    "                            run_in_sample = TRUE,\n",
    "                            s_sq_y = \"mse\",\n",
    "                            sig_sq_est = NULL,\n",
    "                            cov_prior_vec = NULL,\n",
    "                            use_missing_data = TRUE, \n",
    "                            covariates_to_permute = NULL,\n",
    "                            num_rand_samps_in_library = 10000,\n",
    "                            use_missing_data_dummies_as_covars = TRUE,\n",
    "                            replace_missing_data_with_x_j_bar = FALSE,\n",
    "                            impute_missingness_with_rf_impute = FALSE,\n",
    "                            impute_missingness_with_x_j_bar_for_lm = TRUE,\n",
    "                            mem_cache_for_speed = TRUE,\n",
    "                            serialize = TRUE,\n",
    "                            seed = NULL,\n",
    "                            verbose = TRUE)\n",
    "\n",
    "# Print a summary of the results, which includes R2.\n",
    "summary(bart_machine)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Make predictions on the training data. Note: this is not necessary in this case because the bart_machine\n",
    "# object does provide predicted values.  Consider this an example on how to use the \"predict\" function.\n",
    "y_hat <- predict(bart_machine, Xmatrix)\n",
    "\n",
    "# Perform k-fold cross validation using default values.\n",
    "bart_machine_cv5fold <- k_fold_cv(Xmatrix, y, \n",
    "                                  k_folds = 5,\n",
    "                                  folds_vec = NULL, \n",
    "                                  verbose = FALSE, \n",
    "                                  num_trees = 200,\n",
    "                                  num_burn_in = 250,\n",
    "                                  num_iterations_after_burn_in = 1000,\n",
    "                                  alpha = 0.95, beta = 2, k = 2, q = 0.9, nu = 3,\n",
    "                                  prob_rule_class = 0.5,\n",
    "                                  mh_prob_steps = c(2.5, 2.5, 4)/9,\n",
    "                                  use_missing_data = TRUE, \n",
    "                                  use_missing_data_dummies_as_covars = TRUE,\n",
    "                                  serialize = TRUE)\n",
    "\n",
    "# Print R2 and RMSE values.\n",
    "print(bart_machine_cv5fold$PseudoRsq)\n",
    "print(bart_machine_cv5fold$rmse)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Build a BART-CV model by cross-validating over a grid of hyperparameter choices.\n",
    "# Warning: this can take a long time to run.\n",
    "# bartMachine CV win: k: 2 nu, q: 3, 0.99 m: 50\n",
    "bart_machine_CV <- bartMachineCV(Xmatrix, y,\n",
    "                                 num_tree_cvs = c(50, 200), \n",
    "                                 k_cvs = c(2, 3, 5),\n",
    "                                 nu_q_cvs = list(c(3, 0.9), c(3, 0.99), c(10, 0.75)), \n",
    "                                 k_folds = 5, verbose = FALSE,\n",
    "                                 num_burn_in = 250,\n",
    "                                 num_iterations_after_burn_in = 1000,\n",
    "                                 alpha = 0.95, beta = 2,\n",
    "                                 prob_rule_class = 0.5,\n",
    "                                 mh_prob_steps = c(2.5, 2.5, 4)/9,\n",
    "                                 use_missing_data = TRUE, \n",
    "                                 use_missing_data_dummies_as_covars = TRUE,\n",
    "                                 serialize = TRUE)\n",
    "              \n",
    "# Print statistics\n",
    "print(bart_machine_CV$cv_stats)\n",
    "\n",
    "# Save model to a file.\n",
    "saveRDS(bart_machine_CV, file = \"bart_machine_CV.rds\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run a new bartMachine case by reducing beta: this will add more levels to the trees (deeper trees).\n",
    "bart_machine1 <- bartMachine(Xmatrix, y, \n",
    "                            num_trees = 200,\n",
    "                            num_burn_in = 250,\n",
    "                            num_iterations_after_burn_in = 1000,\n",
    "                            alpha = 0.95, beta = 1, k = 2, q = 0.9, nu = 3,\n",
    "                            prob_rule_class = 0.5,\n",
    "                            mh_prob_steps = c(2.5, 2.5, 4)/9,\n",
    "                            debug_log = FALSE,\n",
    "                            run_in_sample = TRUE,\n",
    "                            s_sq_y = \"mse\",\n",
    "                            sig_sq_est = NULL,\n",
    "                            cov_prior_vec = NULL,\n",
    "                            use_missing_data = TRUE, \n",
    "                            covariates_to_permute = NULL,\n",
    "                            num_rand_samps_in_library = 10000,\n",
    "                            use_missing_data_dummies_as_covars = TRUE,\n",
    "                            replace_missing_data_with_x_j_bar = FALSE,\n",
    "                            impute_missingness_with_rf_impute = FALSE,\n",
    "                            impute_missingness_with_x_j_bar_for_lm = TRUE,\n",
    "                            mem_cache_for_speed = TRUE,\n",
    "                            serialize = TRUE,\n",
    "                            seed = NULL,\n",
    "                            verbose = TRUE)  \n",
    "\n",
    "summary(bart_machine1)\n",
    "\n",
    "# Save bartMachine objects to files.  The saveRDS function saves only an object at a time.\n",
    "# Use readRDS() to load the objects back into R.\n",
    "saveRDS(bart_machine, file = \"bart_machine.rds\")\n",
    "saveRDS(bart_machine_cv5fold, file = \"bart_machine_cv5fold.rds\")\n",
    "saveRDS(bart_machine1, file = \"bart_machine_DeeperTrees.rds\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "3.4.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
