# This script testsrunJarFile.R script. It verrifies the Jar file ran properly by checking whether the
# nanoQSAR.csv was created.
# Created: 01/23/2018 Wilson Melendez
# Revised:

test.runJarFile <- function()
{
  # Set the location of the Jar file.
  jar_directory <- main_dir
  
  # Set the name of the file generated by the Jar file.
  jarFileName <- "nanoQSAR.csv"
  
  # Run the script that runs the Jar file.
  runJarFile(jar_directory)
  
  # Check that the file exists.
  checkTrue(file.exists(jarFileName), "File exists.")
  
  # Set the working directory back to the test directory.
  setwd(test_dir)
}